import React from 'react';
import Head from "next/head";
import Header from "../header/header";


const MainLayot = ({children}) => {
    return (
        <div className="mainLayout">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet"/>
            </Head>

            <Header/>
            <main className="main">
                {children}
            </main>
        </div>
);
};

export default MainLayot;

